// Generated by github.com/temporalio/temporal-aws-sdk-generator
// from github.com/aws/aws-sdk-go version 1.35.7

package sagemakerfeaturestoreruntimestub

import (
	"github.com/aws/aws-sdk-go/service/sagemakerfeaturestoreruntime"
	"go.uber.org/cadence/workflow"

	"github.com/banzaicloud/cadence-aws-sdk/clients"
)

// ensure that imports are valid even if not used by the generated code
var _ clients.VoidFuture

type Client interface {
	DeleteRecord(ctx workflow.Context, input *sagemakerfeaturestoreruntime.DeleteRecordInput) (*sagemakerfeaturestoreruntime.DeleteRecordOutput, error)
	DeleteRecordAsync(ctx workflow.Context, input *sagemakerfeaturestoreruntime.DeleteRecordInput) *DeleteRecordFuture

	GetRecord(ctx workflow.Context, input *sagemakerfeaturestoreruntime.GetRecordInput) (*sagemakerfeaturestoreruntime.GetRecordOutput, error)
	GetRecordAsync(ctx workflow.Context, input *sagemakerfeaturestoreruntime.GetRecordInput) *GetRecordFuture

	PutRecord(ctx workflow.Context, input *sagemakerfeaturestoreruntime.PutRecordInput) (*sagemakerfeaturestoreruntime.PutRecordOutput, error)
	PutRecordAsync(ctx workflow.Context, input *sagemakerfeaturestoreruntime.PutRecordInput) *PutRecordFuture
}

func NewClient() Client {
	return &stub{}
}
