// Generated by github.com/temporalio/temporal-aws-sdk-generator
// from github.com/aws/aws-sdk-go version 1.35.7

package pricingstub

import (
	"github.com/aws/aws-sdk-go/service/pricing"
	"go.uber.org/cadence/workflow"

	"github.com/banzaicloud/cadence-aws-sdk/clients"
)

// ensure that imports are valid even if not used by the generated code
var _ clients.VoidFuture

type Client interface {
	DescribeServices(ctx workflow.Context, input *pricing.DescribeServicesInput) (*pricing.DescribeServicesOutput, error)
	DescribeServicesAsync(ctx workflow.Context, input *pricing.DescribeServicesInput) *DescribeServicesFuture

	GetAttributeValues(ctx workflow.Context, input *pricing.GetAttributeValuesInput) (*pricing.GetAttributeValuesOutput, error)
	GetAttributeValuesAsync(ctx workflow.Context, input *pricing.GetAttributeValuesInput) *GetAttributeValuesFuture

	GetProducts(ctx workflow.Context, input *pricing.GetProductsInput) (*pricing.GetProductsOutput, error)
	GetProductsAsync(ctx workflow.Context, input *pricing.GetProductsInput) *GetProductsFuture
}

func NewClient() Client {
	return &stub{}
}
