// Generated by github.com/temporalio/temporal-aws-sdk-generator
// from github.com/aws/aws-sdk-go version 1.35.7

package transcribestreamingservicestub

import (
	"github.com/aws/aws-sdk-go/service/transcribestreamingservice"
	"go.uber.org/cadence/workflow"

	"github.com/banzaicloud/cadence-aws-sdk/clients"
)

// ensure that imports are valid even if not used by the generated code
var _ clients.VoidFuture

type Client interface {
	StartMedicalStreamTranscription(ctx workflow.Context, input *transcribestreamingservice.StartMedicalStreamTranscriptionInput) (*transcribestreamingservice.StartMedicalStreamTranscriptionOutput, error)
	StartMedicalStreamTranscriptionAsync(ctx workflow.Context, input *transcribestreamingservice.StartMedicalStreamTranscriptionInput) *StartMedicalStreamTranscriptionFuture

	StartStreamTranscription(ctx workflow.Context, input *transcribestreamingservice.StartStreamTranscriptionInput) (*transcribestreamingservice.StartStreamTranscriptionOutput, error)
	StartStreamTranscriptionAsync(ctx workflow.Context, input *transcribestreamingservice.StartStreamTranscriptionInput) *StartStreamTranscriptionFuture
}

func NewClient() Client {
	return &stub{}
}
