// Generated by github.com/temporalio/temporal-aws-sdk-generator
// from github.com/aws/aws-sdk-go version 1.35.7

package budgetsstub

import (
	"github.com/aws/aws-sdk-go/service/budgets"
	"go.uber.org/cadence/workflow"

	"github.com/banzaicloud/cadence-aws-sdk/clients"
)

// ensure that imports are valid even if not used by the generated code
var _ clients.VoidFuture

type stub struct{}

type BudgetsCreateBudgetFuture struct {
	// public to support Selector.addFuture
	Future workflow.Future
}

func (r *BudgetsCreateBudgetFuture) Get(ctx workflow.Context) (*budgets.CreateBudgetOutput, error) {
	var output budgets.CreateBudgetOutput
	err := r.Future.Get(ctx, &output)
	return &output, err
}

type BudgetsCreateBudgetActionFuture struct {
	// public to support Selector.addFuture
	Future workflow.Future
}

func (r *BudgetsCreateBudgetActionFuture) Get(ctx workflow.Context) (*budgets.CreateBudgetActionOutput, error) {
	var output budgets.CreateBudgetActionOutput
	err := r.Future.Get(ctx, &output)
	return &output, err
}

type BudgetsCreateNotificationFuture struct {
	// public to support Selector.addFuture
	Future workflow.Future
}

func (r *BudgetsCreateNotificationFuture) Get(ctx workflow.Context) (*budgets.CreateNotificationOutput, error) {
	var output budgets.CreateNotificationOutput
	err := r.Future.Get(ctx, &output)
	return &output, err
}

type BudgetsCreateSubscriberFuture struct {
	// public to support Selector.addFuture
	Future workflow.Future
}

func (r *BudgetsCreateSubscriberFuture) Get(ctx workflow.Context) (*budgets.CreateSubscriberOutput, error) {
	var output budgets.CreateSubscriberOutput
	err := r.Future.Get(ctx, &output)
	return &output, err
}

type BudgetsDeleteBudgetFuture struct {
	// public to support Selector.addFuture
	Future workflow.Future
}

func (r *BudgetsDeleteBudgetFuture) Get(ctx workflow.Context) (*budgets.DeleteBudgetOutput, error) {
	var output budgets.DeleteBudgetOutput
	err := r.Future.Get(ctx, &output)
	return &output, err
}

type BudgetsDeleteBudgetActionFuture struct {
	// public to support Selector.addFuture
	Future workflow.Future
}

func (r *BudgetsDeleteBudgetActionFuture) Get(ctx workflow.Context) (*budgets.DeleteBudgetActionOutput, error) {
	var output budgets.DeleteBudgetActionOutput
	err := r.Future.Get(ctx, &output)
	return &output, err
}

type BudgetsDeleteNotificationFuture struct {
	// public to support Selector.addFuture
	Future workflow.Future
}

func (r *BudgetsDeleteNotificationFuture) Get(ctx workflow.Context) (*budgets.DeleteNotificationOutput, error) {
	var output budgets.DeleteNotificationOutput
	err := r.Future.Get(ctx, &output)
	return &output, err
}

type BudgetsDeleteSubscriberFuture struct {
	// public to support Selector.addFuture
	Future workflow.Future
}

func (r *BudgetsDeleteSubscriberFuture) Get(ctx workflow.Context) (*budgets.DeleteSubscriberOutput, error) {
	var output budgets.DeleteSubscriberOutput
	err := r.Future.Get(ctx, &output)
	return &output, err
}

type BudgetsDescribeBudgetFuture struct {
	// public to support Selector.addFuture
	Future workflow.Future
}

func (r *BudgetsDescribeBudgetFuture) Get(ctx workflow.Context) (*budgets.DescribeBudgetOutput, error) {
	var output budgets.DescribeBudgetOutput
	err := r.Future.Get(ctx, &output)
	return &output, err
}

type BudgetsDescribeBudgetActionFuture struct {
	// public to support Selector.addFuture
	Future workflow.Future
}

func (r *BudgetsDescribeBudgetActionFuture) Get(ctx workflow.Context) (*budgets.DescribeBudgetActionOutput, error) {
	var output budgets.DescribeBudgetActionOutput
	err := r.Future.Get(ctx, &output)
	return &output, err
}

type BudgetsDescribeBudgetActionHistoriesFuture struct {
	// public to support Selector.addFuture
	Future workflow.Future
}

func (r *BudgetsDescribeBudgetActionHistoriesFuture) Get(ctx workflow.Context) (*budgets.DescribeBudgetActionHistoriesOutput, error) {
	var output budgets.DescribeBudgetActionHistoriesOutput
	err := r.Future.Get(ctx, &output)
	return &output, err
}

type BudgetsDescribeBudgetActionsForAccountFuture struct {
	// public to support Selector.addFuture
	Future workflow.Future
}

func (r *BudgetsDescribeBudgetActionsForAccountFuture) Get(ctx workflow.Context) (*budgets.DescribeBudgetActionsForAccountOutput, error) {
	var output budgets.DescribeBudgetActionsForAccountOutput
	err := r.Future.Get(ctx, &output)
	return &output, err
}

type BudgetsDescribeBudgetActionsForBudgetFuture struct {
	// public to support Selector.addFuture
	Future workflow.Future
}

func (r *BudgetsDescribeBudgetActionsForBudgetFuture) Get(ctx workflow.Context) (*budgets.DescribeBudgetActionsForBudgetOutput, error) {
	var output budgets.DescribeBudgetActionsForBudgetOutput
	err := r.Future.Get(ctx, &output)
	return &output, err
}

type BudgetsDescribeBudgetPerformanceHistoryFuture struct {
	// public to support Selector.addFuture
	Future workflow.Future
}

func (r *BudgetsDescribeBudgetPerformanceHistoryFuture) Get(ctx workflow.Context) (*budgets.DescribeBudgetPerformanceHistoryOutput, error) {
	var output budgets.DescribeBudgetPerformanceHistoryOutput
	err := r.Future.Get(ctx, &output)
	return &output, err
}

type BudgetsDescribeBudgetsFuture struct {
	// public to support Selector.addFuture
	Future workflow.Future
}

func (r *BudgetsDescribeBudgetsFuture) Get(ctx workflow.Context) (*budgets.DescribeBudgetsOutput, error) {
	var output budgets.DescribeBudgetsOutput
	err := r.Future.Get(ctx, &output)
	return &output, err
}

type BudgetsDescribeNotificationsForBudgetFuture struct {
	// public to support Selector.addFuture
	Future workflow.Future
}

func (r *BudgetsDescribeNotificationsForBudgetFuture) Get(ctx workflow.Context) (*budgets.DescribeNotificationsForBudgetOutput, error) {
	var output budgets.DescribeNotificationsForBudgetOutput
	err := r.Future.Get(ctx, &output)
	return &output, err
}

type BudgetsDescribeSubscribersForNotificationFuture struct {
	// public to support Selector.addFuture
	Future workflow.Future
}

func (r *BudgetsDescribeSubscribersForNotificationFuture) Get(ctx workflow.Context) (*budgets.DescribeSubscribersForNotificationOutput, error) {
	var output budgets.DescribeSubscribersForNotificationOutput
	err := r.Future.Get(ctx, &output)
	return &output, err
}

type BudgetsExecuteBudgetActionFuture struct {
	// public to support Selector.addFuture
	Future workflow.Future
}

func (r *BudgetsExecuteBudgetActionFuture) Get(ctx workflow.Context) (*budgets.ExecuteBudgetActionOutput, error) {
	var output budgets.ExecuteBudgetActionOutput
	err := r.Future.Get(ctx, &output)
	return &output, err
}

type BudgetsUpdateBudgetFuture struct {
	// public to support Selector.addFuture
	Future workflow.Future
}

func (r *BudgetsUpdateBudgetFuture) Get(ctx workflow.Context) (*budgets.UpdateBudgetOutput, error) {
	var output budgets.UpdateBudgetOutput
	err := r.Future.Get(ctx, &output)
	return &output, err
}

type BudgetsUpdateBudgetActionFuture struct {
	// public to support Selector.addFuture
	Future workflow.Future
}

func (r *BudgetsUpdateBudgetActionFuture) Get(ctx workflow.Context) (*budgets.UpdateBudgetActionOutput, error) {
	var output budgets.UpdateBudgetActionOutput
	err := r.Future.Get(ctx, &output)
	return &output, err
}

type BudgetsUpdateNotificationFuture struct {
	// public to support Selector.addFuture
	Future workflow.Future
}

func (r *BudgetsUpdateNotificationFuture) Get(ctx workflow.Context) (*budgets.UpdateNotificationOutput, error) {
	var output budgets.UpdateNotificationOutput
	err := r.Future.Get(ctx, &output)
	return &output, err
}

type BudgetsUpdateSubscriberFuture struct {
	// public to support Selector.addFuture
	Future workflow.Future
}

func (r *BudgetsUpdateSubscriberFuture) Get(ctx workflow.Context) (*budgets.UpdateSubscriberOutput, error) {
	var output budgets.UpdateSubscriberOutput
	err := r.Future.Get(ctx, &output)
	return &output, err
}

func (a *stub) CreateBudget(ctx workflow.Context, input *budgets.CreateBudgetInput) (*budgets.CreateBudgetOutput, error) {
	var output budgets.CreateBudgetOutput
	err := workflow.ExecuteActivity(ctx, "aws-budgets-CreateBudget", input).Get(ctx, &output)
	return &output, err
}

func (a *stub) CreateBudgetAsync(ctx workflow.Context, input *budgets.CreateBudgetInput) *BudgetsCreateBudgetFuture {
	future := workflow.ExecuteActivity(ctx, "aws-budgets-CreateBudget", input)
	return &BudgetsCreateBudgetFuture{Future: future}
}

func (a *stub) CreateBudgetAction(ctx workflow.Context, input *budgets.CreateBudgetActionInput) (*budgets.CreateBudgetActionOutput, error) {
	var output budgets.CreateBudgetActionOutput
	err := workflow.ExecuteActivity(ctx, "aws-budgets-CreateBudgetAction", input).Get(ctx, &output)
	return &output, err
}

func (a *stub) CreateBudgetActionAsync(ctx workflow.Context, input *budgets.CreateBudgetActionInput) *BudgetsCreateBudgetActionFuture {
	future := workflow.ExecuteActivity(ctx, "aws-budgets-CreateBudgetAction", input)
	return &BudgetsCreateBudgetActionFuture{Future: future}
}

func (a *stub) CreateNotification(ctx workflow.Context, input *budgets.CreateNotificationInput) (*budgets.CreateNotificationOutput, error) {
	var output budgets.CreateNotificationOutput
	err := workflow.ExecuteActivity(ctx, "aws-budgets-CreateNotification", input).Get(ctx, &output)
	return &output, err
}

func (a *stub) CreateNotificationAsync(ctx workflow.Context, input *budgets.CreateNotificationInput) *BudgetsCreateNotificationFuture {
	future := workflow.ExecuteActivity(ctx, "aws-budgets-CreateNotification", input)
	return &BudgetsCreateNotificationFuture{Future: future}
}

func (a *stub) CreateSubscriber(ctx workflow.Context, input *budgets.CreateSubscriberInput) (*budgets.CreateSubscriberOutput, error) {
	var output budgets.CreateSubscriberOutput
	err := workflow.ExecuteActivity(ctx, "aws-budgets-CreateSubscriber", input).Get(ctx, &output)
	return &output, err
}

func (a *stub) CreateSubscriberAsync(ctx workflow.Context, input *budgets.CreateSubscriberInput) *BudgetsCreateSubscriberFuture {
	future := workflow.ExecuteActivity(ctx, "aws-budgets-CreateSubscriber", input)
	return &BudgetsCreateSubscriberFuture{Future: future}
}

func (a *stub) DeleteBudget(ctx workflow.Context, input *budgets.DeleteBudgetInput) (*budgets.DeleteBudgetOutput, error) {
	var output budgets.DeleteBudgetOutput
	err := workflow.ExecuteActivity(ctx, "aws-budgets-DeleteBudget", input).Get(ctx, &output)
	return &output, err
}

func (a *stub) DeleteBudgetAsync(ctx workflow.Context, input *budgets.DeleteBudgetInput) *BudgetsDeleteBudgetFuture {
	future := workflow.ExecuteActivity(ctx, "aws-budgets-DeleteBudget", input)
	return &BudgetsDeleteBudgetFuture{Future: future}
}

func (a *stub) DeleteBudgetAction(ctx workflow.Context, input *budgets.DeleteBudgetActionInput) (*budgets.DeleteBudgetActionOutput, error) {
	var output budgets.DeleteBudgetActionOutput
	err := workflow.ExecuteActivity(ctx, "aws-budgets-DeleteBudgetAction", input).Get(ctx, &output)
	return &output, err
}

func (a *stub) DeleteBudgetActionAsync(ctx workflow.Context, input *budgets.DeleteBudgetActionInput) *BudgetsDeleteBudgetActionFuture {
	future := workflow.ExecuteActivity(ctx, "aws-budgets-DeleteBudgetAction", input)
	return &BudgetsDeleteBudgetActionFuture{Future: future}
}

func (a *stub) DeleteNotification(ctx workflow.Context, input *budgets.DeleteNotificationInput) (*budgets.DeleteNotificationOutput, error) {
	var output budgets.DeleteNotificationOutput
	err := workflow.ExecuteActivity(ctx, "aws-budgets-DeleteNotification", input).Get(ctx, &output)
	return &output, err
}

func (a *stub) DeleteNotificationAsync(ctx workflow.Context, input *budgets.DeleteNotificationInput) *BudgetsDeleteNotificationFuture {
	future := workflow.ExecuteActivity(ctx, "aws-budgets-DeleteNotification", input)
	return &BudgetsDeleteNotificationFuture{Future: future}
}

func (a *stub) DeleteSubscriber(ctx workflow.Context, input *budgets.DeleteSubscriberInput) (*budgets.DeleteSubscriberOutput, error) {
	var output budgets.DeleteSubscriberOutput
	err := workflow.ExecuteActivity(ctx, "aws-budgets-DeleteSubscriber", input).Get(ctx, &output)
	return &output, err
}

func (a *stub) DeleteSubscriberAsync(ctx workflow.Context, input *budgets.DeleteSubscriberInput) *BudgetsDeleteSubscriberFuture {
	future := workflow.ExecuteActivity(ctx, "aws-budgets-DeleteSubscriber", input)
	return &BudgetsDeleteSubscriberFuture{Future: future}
}

func (a *stub) DescribeBudget(ctx workflow.Context, input *budgets.DescribeBudgetInput) (*budgets.DescribeBudgetOutput, error) {
	var output budgets.DescribeBudgetOutput
	err := workflow.ExecuteActivity(ctx, "aws-budgets-DescribeBudget", input).Get(ctx, &output)
	return &output, err
}

func (a *stub) DescribeBudgetAsync(ctx workflow.Context, input *budgets.DescribeBudgetInput) *BudgetsDescribeBudgetFuture {
	future := workflow.ExecuteActivity(ctx, "aws-budgets-DescribeBudget", input)
	return &BudgetsDescribeBudgetFuture{Future: future}
}

func (a *stub) DescribeBudgetAction(ctx workflow.Context, input *budgets.DescribeBudgetActionInput) (*budgets.DescribeBudgetActionOutput, error) {
	var output budgets.DescribeBudgetActionOutput
	err := workflow.ExecuteActivity(ctx, "aws-budgets-DescribeBudgetAction", input).Get(ctx, &output)
	return &output, err
}

func (a *stub) DescribeBudgetActionAsync(ctx workflow.Context, input *budgets.DescribeBudgetActionInput) *BudgetsDescribeBudgetActionFuture {
	future := workflow.ExecuteActivity(ctx, "aws-budgets-DescribeBudgetAction", input)
	return &BudgetsDescribeBudgetActionFuture{Future: future}
}

func (a *stub) DescribeBudgetActionHistories(ctx workflow.Context, input *budgets.DescribeBudgetActionHistoriesInput) (*budgets.DescribeBudgetActionHistoriesOutput, error) {
	var output budgets.DescribeBudgetActionHistoriesOutput
	err := workflow.ExecuteActivity(ctx, "aws-budgets-DescribeBudgetActionHistories", input).Get(ctx, &output)
	return &output, err
}

func (a *stub) DescribeBudgetActionHistoriesAsync(ctx workflow.Context, input *budgets.DescribeBudgetActionHistoriesInput) *BudgetsDescribeBudgetActionHistoriesFuture {
	future := workflow.ExecuteActivity(ctx, "aws-budgets-DescribeBudgetActionHistories", input)
	return &BudgetsDescribeBudgetActionHistoriesFuture{Future: future}
}

func (a *stub) DescribeBudgetActionsForAccount(ctx workflow.Context, input *budgets.DescribeBudgetActionsForAccountInput) (*budgets.DescribeBudgetActionsForAccountOutput, error) {
	var output budgets.DescribeBudgetActionsForAccountOutput
	err := workflow.ExecuteActivity(ctx, "aws-budgets-DescribeBudgetActionsForAccount", input).Get(ctx, &output)
	return &output, err
}

func (a *stub) DescribeBudgetActionsForAccountAsync(ctx workflow.Context, input *budgets.DescribeBudgetActionsForAccountInput) *BudgetsDescribeBudgetActionsForAccountFuture {
	future := workflow.ExecuteActivity(ctx, "aws-budgets-DescribeBudgetActionsForAccount", input)
	return &BudgetsDescribeBudgetActionsForAccountFuture{Future: future}
}

func (a *stub) DescribeBudgetActionsForBudget(ctx workflow.Context, input *budgets.DescribeBudgetActionsForBudgetInput) (*budgets.DescribeBudgetActionsForBudgetOutput, error) {
	var output budgets.DescribeBudgetActionsForBudgetOutput
	err := workflow.ExecuteActivity(ctx, "aws-budgets-DescribeBudgetActionsForBudget", input).Get(ctx, &output)
	return &output, err
}

func (a *stub) DescribeBudgetActionsForBudgetAsync(ctx workflow.Context, input *budgets.DescribeBudgetActionsForBudgetInput) *BudgetsDescribeBudgetActionsForBudgetFuture {
	future := workflow.ExecuteActivity(ctx, "aws-budgets-DescribeBudgetActionsForBudget", input)
	return &BudgetsDescribeBudgetActionsForBudgetFuture{Future: future}
}

func (a *stub) DescribeBudgetPerformanceHistory(ctx workflow.Context, input *budgets.DescribeBudgetPerformanceHistoryInput) (*budgets.DescribeBudgetPerformanceHistoryOutput, error) {
	var output budgets.DescribeBudgetPerformanceHistoryOutput
	err := workflow.ExecuteActivity(ctx, "aws-budgets-DescribeBudgetPerformanceHistory", input).Get(ctx, &output)
	return &output, err
}

func (a *stub) DescribeBudgetPerformanceHistoryAsync(ctx workflow.Context, input *budgets.DescribeBudgetPerformanceHistoryInput) *BudgetsDescribeBudgetPerformanceHistoryFuture {
	future := workflow.ExecuteActivity(ctx, "aws-budgets-DescribeBudgetPerformanceHistory", input)
	return &BudgetsDescribeBudgetPerformanceHistoryFuture{Future: future}
}

func (a *stub) DescribeBudgets(ctx workflow.Context, input *budgets.DescribeBudgetsInput) (*budgets.DescribeBudgetsOutput, error) {
	var output budgets.DescribeBudgetsOutput
	err := workflow.ExecuteActivity(ctx, "aws-budgets-DescribeBudgets", input).Get(ctx, &output)
	return &output, err
}

func (a *stub) DescribeBudgetsAsync(ctx workflow.Context, input *budgets.DescribeBudgetsInput) *BudgetsDescribeBudgetsFuture {
	future := workflow.ExecuteActivity(ctx, "aws-budgets-DescribeBudgets", input)
	return &BudgetsDescribeBudgetsFuture{Future: future}
}

func (a *stub) DescribeNotificationsForBudget(ctx workflow.Context, input *budgets.DescribeNotificationsForBudgetInput) (*budgets.DescribeNotificationsForBudgetOutput, error) {
	var output budgets.DescribeNotificationsForBudgetOutput
	err := workflow.ExecuteActivity(ctx, "aws-budgets-DescribeNotificationsForBudget", input).Get(ctx, &output)
	return &output, err
}

func (a *stub) DescribeNotificationsForBudgetAsync(ctx workflow.Context, input *budgets.DescribeNotificationsForBudgetInput) *BudgetsDescribeNotificationsForBudgetFuture {
	future := workflow.ExecuteActivity(ctx, "aws-budgets-DescribeNotificationsForBudget", input)
	return &BudgetsDescribeNotificationsForBudgetFuture{Future: future}
}

func (a *stub) DescribeSubscribersForNotification(ctx workflow.Context, input *budgets.DescribeSubscribersForNotificationInput) (*budgets.DescribeSubscribersForNotificationOutput, error) {
	var output budgets.DescribeSubscribersForNotificationOutput
	err := workflow.ExecuteActivity(ctx, "aws-budgets-DescribeSubscribersForNotification", input).Get(ctx, &output)
	return &output, err
}

func (a *stub) DescribeSubscribersForNotificationAsync(ctx workflow.Context, input *budgets.DescribeSubscribersForNotificationInput) *BudgetsDescribeSubscribersForNotificationFuture {
	future := workflow.ExecuteActivity(ctx, "aws-budgets-DescribeSubscribersForNotification", input)
	return &BudgetsDescribeSubscribersForNotificationFuture{Future: future}
}

func (a *stub) ExecuteBudgetAction(ctx workflow.Context, input *budgets.ExecuteBudgetActionInput) (*budgets.ExecuteBudgetActionOutput, error) {
	var output budgets.ExecuteBudgetActionOutput
	err := workflow.ExecuteActivity(ctx, "aws-budgets-ExecuteBudgetAction", input).Get(ctx, &output)
	return &output, err
}

func (a *stub) ExecuteBudgetActionAsync(ctx workflow.Context, input *budgets.ExecuteBudgetActionInput) *BudgetsExecuteBudgetActionFuture {
	future := workflow.ExecuteActivity(ctx, "aws-budgets-ExecuteBudgetAction", input)
	return &BudgetsExecuteBudgetActionFuture{Future: future}
}

func (a *stub) UpdateBudget(ctx workflow.Context, input *budgets.UpdateBudgetInput) (*budgets.UpdateBudgetOutput, error) {
	var output budgets.UpdateBudgetOutput
	err := workflow.ExecuteActivity(ctx, "aws-budgets-UpdateBudget", input).Get(ctx, &output)
	return &output, err
}

func (a *stub) UpdateBudgetAsync(ctx workflow.Context, input *budgets.UpdateBudgetInput) *BudgetsUpdateBudgetFuture {
	future := workflow.ExecuteActivity(ctx, "aws-budgets-UpdateBudget", input)
	return &BudgetsUpdateBudgetFuture{Future: future}
}

func (a *stub) UpdateBudgetAction(ctx workflow.Context, input *budgets.UpdateBudgetActionInput) (*budgets.UpdateBudgetActionOutput, error) {
	var output budgets.UpdateBudgetActionOutput
	err := workflow.ExecuteActivity(ctx, "aws-budgets-UpdateBudgetAction", input).Get(ctx, &output)
	return &output, err
}

func (a *stub) UpdateBudgetActionAsync(ctx workflow.Context, input *budgets.UpdateBudgetActionInput) *BudgetsUpdateBudgetActionFuture {
	future := workflow.ExecuteActivity(ctx, "aws-budgets-UpdateBudgetAction", input)
	return &BudgetsUpdateBudgetActionFuture{Future: future}
}

func (a *stub) UpdateNotification(ctx workflow.Context, input *budgets.UpdateNotificationInput) (*budgets.UpdateNotificationOutput, error) {
	var output budgets.UpdateNotificationOutput
	err := workflow.ExecuteActivity(ctx, "aws-budgets-UpdateNotification", input).Get(ctx, &output)
	return &output, err
}

func (a *stub) UpdateNotificationAsync(ctx workflow.Context, input *budgets.UpdateNotificationInput) *BudgetsUpdateNotificationFuture {
	future := workflow.ExecuteActivity(ctx, "aws-budgets-UpdateNotification", input)
	return &BudgetsUpdateNotificationFuture{Future: future}
}

func (a *stub) UpdateSubscriber(ctx workflow.Context, input *budgets.UpdateSubscriberInput) (*budgets.UpdateSubscriberOutput, error) {
	var output budgets.UpdateSubscriberOutput
	err := workflow.ExecuteActivity(ctx, "aws-budgets-UpdateSubscriber", input).Get(ctx, &output)
	return &output, err
}

func (a *stub) UpdateSubscriberAsync(ctx workflow.Context, input *budgets.UpdateSubscriberInput) *BudgetsUpdateSubscriberFuture {
	future := workflow.ExecuteActivity(ctx, "aws-budgets-UpdateSubscriber", input)
	return &BudgetsUpdateSubscriberFuture{Future: future}
}
