// Generated by github.com/temporalio/temporal-aws-sdk-generator
// from github.com/aws/aws-sdk-go version 1.35.7

package iotdeviceadvisorstub

import (
	"github.com/aws/aws-sdk-go/service/iotdeviceadvisor"
	"go.uber.org/cadence/workflow"

	"github.com/banzaicloud/cadence-aws-sdk/clients"
)

// ensure that imports are valid even if not used by the generated code
var _ clients.VoidFuture

type Client interface {
	CreateSuiteDefinition(ctx workflow.Context, input *iotdeviceadvisor.CreateSuiteDefinitionInput) (*iotdeviceadvisor.CreateSuiteDefinitionOutput, error)
	CreateSuiteDefinitionAsync(ctx workflow.Context, input *iotdeviceadvisor.CreateSuiteDefinitionInput) *CreateSuiteDefinitionFuture

	DeleteSuiteDefinition(ctx workflow.Context, input *iotdeviceadvisor.DeleteSuiteDefinitionInput) (*iotdeviceadvisor.DeleteSuiteDefinitionOutput, error)
	DeleteSuiteDefinitionAsync(ctx workflow.Context, input *iotdeviceadvisor.DeleteSuiteDefinitionInput) *DeleteSuiteDefinitionFuture

	GetSuiteDefinition(ctx workflow.Context, input *iotdeviceadvisor.GetSuiteDefinitionInput) (*iotdeviceadvisor.GetSuiteDefinitionOutput, error)
	GetSuiteDefinitionAsync(ctx workflow.Context, input *iotdeviceadvisor.GetSuiteDefinitionInput) *GetSuiteDefinitionFuture

	GetSuiteRun(ctx workflow.Context, input *iotdeviceadvisor.GetSuiteRunInput) (*iotdeviceadvisor.GetSuiteRunOutput, error)
	GetSuiteRunAsync(ctx workflow.Context, input *iotdeviceadvisor.GetSuiteRunInput) *GetSuiteRunFuture

	GetSuiteRunReport(ctx workflow.Context, input *iotdeviceadvisor.GetSuiteRunReportInput) (*iotdeviceadvisor.GetSuiteRunReportOutput, error)
	GetSuiteRunReportAsync(ctx workflow.Context, input *iotdeviceadvisor.GetSuiteRunReportInput) *GetSuiteRunReportFuture

	ListSuiteDefinitions(ctx workflow.Context, input *iotdeviceadvisor.ListSuiteDefinitionsInput) (*iotdeviceadvisor.ListSuiteDefinitionsOutput, error)
	ListSuiteDefinitionsAsync(ctx workflow.Context, input *iotdeviceadvisor.ListSuiteDefinitionsInput) *ListSuiteDefinitionsFuture

	ListSuiteRuns(ctx workflow.Context, input *iotdeviceadvisor.ListSuiteRunsInput) (*iotdeviceadvisor.ListSuiteRunsOutput, error)
	ListSuiteRunsAsync(ctx workflow.Context, input *iotdeviceadvisor.ListSuiteRunsInput) *ListSuiteRunsFuture

	ListTagsForResource(ctx workflow.Context, input *iotdeviceadvisor.ListTagsForResourceInput) (*iotdeviceadvisor.ListTagsForResourceOutput, error)
	ListTagsForResourceAsync(ctx workflow.Context, input *iotdeviceadvisor.ListTagsForResourceInput) *ListTagsForResourceFuture

	ListTestCases(ctx workflow.Context, input *iotdeviceadvisor.ListTestCasesInput) (*iotdeviceadvisor.ListTestCasesOutput, error)
	ListTestCasesAsync(ctx workflow.Context, input *iotdeviceadvisor.ListTestCasesInput) *ListTestCasesFuture

	StartSuiteRun(ctx workflow.Context, input *iotdeviceadvisor.StartSuiteRunInput) (*iotdeviceadvisor.StartSuiteRunOutput, error)
	StartSuiteRunAsync(ctx workflow.Context, input *iotdeviceadvisor.StartSuiteRunInput) *StartSuiteRunFuture

	TagResource(ctx workflow.Context, input *iotdeviceadvisor.TagResourceInput) (*iotdeviceadvisor.TagResourceOutput, error)
	TagResourceAsync(ctx workflow.Context, input *iotdeviceadvisor.TagResourceInput) *TagResourceFuture

	UntagResource(ctx workflow.Context, input *iotdeviceadvisor.UntagResourceInput) (*iotdeviceadvisor.UntagResourceOutput, error)
	UntagResourceAsync(ctx workflow.Context, input *iotdeviceadvisor.UntagResourceInput) *UntagResourceFuture

	UpdateSuiteDefinition(ctx workflow.Context, input *iotdeviceadvisor.UpdateSuiteDefinitionInput) (*iotdeviceadvisor.UpdateSuiteDefinitionOutput, error)
	UpdateSuiteDefinitionAsync(ctx workflow.Context, input *iotdeviceadvisor.UpdateSuiteDefinitionInput) *UpdateSuiteDefinitionFuture
}

func NewClient() Client {
	return &stub{}
}
